# Displays available recipes by running `just -l`.
setup:
  #!/usr/bin/env bash
  just -l

# install
i: 
  bun install

# Run tests
t:
  bun test

fmt: 
  bun run prettier --write src

run *ARGS:
  bun run src/cli.ts {{ARGS}}
